### ISSUE TITLE
Correct & rich handling of all clickEvent text

### ISSUE THREAD

**Issue by Ellivers** [SpyglassMC/Spyglass#1001]
Example command:
```mcfunction
tellraw @s {"text":"test","clickEvent":{"action":"suggest_command","value":"/item modify enti"}}
```

This does not cause the function to fail to load, so it should not cause an error. A warning would be more acceptable.

While an invalid command with the `run_command` action does not cause the function to fail either, it has more reason to cause an error, since clicking the text and therefore running the command would do so.

**Comment by misode** [comment]
Already fixed in v4.0

**Comment by shap-po** [comment]
it seems like this issue is back

![image](https://github.com/user-attachments/assets/1348989d-45d1-42b0-9c47-4e27ec921c6d)
