### ISSUE TITLE
gamerule enderPearlsVanishOnDeath does not exist

### ISSUE THREAD

**Issue by ChenCMD** [SpyglassMC/Spyglass#1087]
SSIA

**Comment by InQuognito** [comment]
fixed in https://github.com/SpyglassMC/Spyglass/pull/1083

**Comment by misode** [comment]
A new extension version `v3.4.19` has been released, which fixes this issue 🎉

**Comment by dragon3025** [comment]
I'm using v3.4.19 and this isn't fixed.
![1](https://github.com/SpyglassMC/Spyglass/assets/11652210/a8cb7345-4bfc-4283-a29b-4d93fea7e7e6)
![2](https://github.com/SpyglassMC/Spyglass/assets/11652210/e174085b-9403-4def-b43c-a5661e0b0ba3)
![3](https://github.com/SpyglassMC/Spyglass/assets/11652210/7df37484-cb49-46b8-8efc-c90a070e8cb4)

**Comment by MulverineX** [comment]
Found the problem here, CommandTree 1.20.3 was started with a copy from 1.20 not 1.20.2. Will be fixed in v4.
